#!/usr/bin/env python

# adapted from: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/logging/cloud-client/snippets.py

import argparse

from google.cloud import logging


def write_entry(logger_name, message):
    """Writes log entries to the given logger."""
    logging_client = logging.Client()

    # This log can be found in the Cloud Logging console under 'Custom Logs'.
    logger = logging_client.logger(logger_name)

    # Make a simple text log
    logger.log_text(message)

    # Simple text log with severity.
    # logger.log_text('Goodbye, world!', severity='ERROR')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        'logger_name', help='Logger name', default='example_log')
    parser.add_argument(
        'message', help='Message to log', default='')
    subparsers = parser.add_subparsers(dest='command')
    subparsers.add_parser('write', help=write_entry.__doc__)

    args = parser.parse_args()

    if args.command == 'write':
        write_entry(args.logger_name, args.message)
